# Generated by Django 2.0.7 on 2018-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20180711_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=50)),
                ('stu_phone_no', models.CharField(max_length=40)),
                ('stu_dob', models.DateField()),
            ],
        ),
    ]
